[phases.setup]
nixPkgs = ["python311", "nodejs-18_x"]

[phases.install]
cmds = [
  "cd Support_Page_Design/backend && pip install -e .",
  "cd Support_Page_Design && npm install"
]

[phases.build]
cmds = [
  "cd Support_Page_Design && npm run build"
]

[start]
cmd = "cd Support_Page_Design/backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT"
